### ISSUE TITLE
Fixws is unlicensed

### ISSUE THREAD

**Issue by kmk3** [ntc2/conf#1]
Hello, I recently stumbled upon your [answer on SO](https://stackoverflow.com/a/15398512) and your [fixws alias](https://github.com/ntc2/conf/blob/7fc338143bcd10984605c6e7bb86ac88df71a7a2/dot.gitconfig#L267).

The aliases seem to be pretty comprehensive, so I would like to turn them into
shell scripts.

That way, I could do the following:
- Version them in their own repo
- Use the repo as a submodule inside a versioned custom hooks dir
  (i.e.: with core.hooksPath)

- Call them in a pre-commit hook
- Stop worrying about new whitespace errors (hopefully)

Or something similar.

But even though [the README says](https://github.com/ntc2/conf/blob/de92093a4e3eda4fbde5a33209b1c08b32479eca/README#L1) "Maybe other people will find them useful",
neither the repository nor the alises seem to be under any license.

So, would you mind licensing the repo or at least [dot.gitconfig](https://github.com/ntc2/conf/blob/master/dot.gitconfig) under a free software
license, such as MIT?

**Comment by ntc2** [comment]
Sorry about the slow fix: I was not subscribed to notifications on this repo, so I didn't know about your issue until today. Thanks @kmk3!

**Comment by kmk3** [comment]
Thank you!

>Sorry about the slow fix

No worries.

**Comment by kmk3** [comment]
https://github.com/ntc2/conf/blob/master/LICENSE#L3
Nitpick (disregard this if you want): If I understand it correctly, copyright
applies to every year that had a contribution, so I suppose that the third line
would be more acurrate as "Copyright (C) 2005-2018 Nathan Collins".

**Comment by ntc2** [comment]
I changed it to "2005-NOW".
